#!/usr/bin/env python3
"""Train small linear eval and move-ranker baselines from JSONL labels."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import bulletchess as bc
import numpy as np

from lulzfish_env import FEATURE_SIZE, action_from_uci, extract_features


MOVE_FEATURE_SIZE = 32


def load_records(path: Path) -> list[dict]:
    records: list[dict] = []
    with path.open("r", encoding="utf-8") as src:
        for line in src:
            if line.strip():
                records.append(json.loads(line))
    if not records:
        raise ValueError(f"no records in {path}")
    return records


def train_ridge(features: np.ndarray, targets: np.ndarray, l2: float) -> np.ndarray:
    x = np.concatenate([features, np.ones((features.shape[0], 1), dtype=np.float64)], axis=1).astype(np.float64)
    y = targets.astype(np.float64)
    xtx = np.einsum("ni,nj->ij", x, x, optimize=True)
    reg = np.eye(xtx.shape[0], dtype=np.float64) * l2
    reg[-1, -1] = 0.0
    xty = np.einsum("ni,n->i", x, y, optimize=True)
    return np.linalg.solve(xtx + reg, xty)


def train_eval(records: list[dict], l2: float) -> dict:
    xs = []
    ys = []
    for record in records:
        board = bc.Board.from_fen(record["fen"])
        xs.append(extract_features(board, record.get("ply", 0)))
        ys.append(np.clip(record["target_score_cp"], -3000, 3000) / 100.0)
    weights = train_ridge(np.stack(xs), np.asarray(ys, dtype=np.float32), l2)
    return {
        "kind": "graph_eval_linear",
        "feature_size": FEATURE_SIZE,
        "scale": "target_score_cp / 100",
        "weights": weights[:-1].astype(float).tolist(),
        "bias": float(weights[-1]),
    }


def move_features(board: bc.Board, move_text: str, rank: int) -> np.ndarray:
    move = bc.Move.from_uci(move_text)
    piece = board[move.origin]
    victim = board[move.destination]
    out = np.zeros(MOVE_FEATURE_SIZE, dtype=np.float32)
    from_sq = move.origin.index()
    to_sq = move.destination.index()
    out[0] = (from_sq & 7) / 7.0
    out[1] = (from_sq >> 3) / 7.0
    out[2] = (to_sq & 7) / 7.0
    out[3] = (to_sq >> 3) / 7.0
    out[4] = float(bool(move.is_capture(board)))
    out[5] = float(move.is_promotion())
    out[6] = float(bool(move.is_castling(board)))
    out[7] = min(rank, 64) / 64.0
    if piece is not None:
        type_index = [bc.PAWN, bc.KNIGHT, bc.BISHOP, bc.ROOK, bc.QUEEN, bc.KING].index(piece.piece_type)
        out[8 + type_index] = 1.0
    if victim is not None:
        type_index = [bc.PAWN, bc.KNIGHT, bc.BISHOP, bc.ROOK, bc.QUEEN, bc.KING].index(victim.piece_type)
        out[14 + type_index] = 1.0

    copy = board.copy()
    if move in copy.legal_moves():
        copy.apply(move)
        out[20] = float(copy in bc.CHECK)
    out[21] = abs((to_sq & 7) - 3.5) / 3.5
    out[22] = abs((to_sq >> 3) - 3.5) / 3.5
    return out


def train_move_ranker(records: list[dict], l2: float) -> dict:
    xs = []
    ys = []
    for record in records:
        board = bc.Board.from_fen(record["fen"])
        target = record["target_bestmove"]
        for rank, move_text in enumerate(record["legal_moves"]):
            xs.append(move_features(board, move_text, rank))
            ys.append(1.0 if move_text == target else 0.0)
    weights = train_ridge(np.stack(xs), np.asarray(ys, dtype=np.float32), l2)
    return {
        "kind": "search_move_ranker_linear",
        "feature_size": MOVE_FEATURE_SIZE,
        "label": "1 for target_depth bestmove, 0 for other legal moves",
        "weights": weights[:-1].astype(float).tolist(),
        "bias": float(weights[-1]),
    }


def write_cpp_header(path: Path, eval_model: dict, ranker_model: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    def array_text(values: list[float]) -> str:
        return ", ".join(f"{value:.8g}f" for value in values)

    text = f"""#pragma once

// Generated by tools/rl/train_linear_models.py.
// Baseline training artifact only; integrate deliberately after measurement.

#include <array>

namespace lulzfish::eval::learned {{

inline constexpr int GRAPH_EVAL_LINEAR_FEATURES = {eval_model["feature_size"]};
inline constexpr float GRAPH_EVAL_LINEAR_BIAS = {eval_model["bias"]:.8g}f;
inline constexpr std::array<float, GRAPH_EVAL_LINEAR_FEATURES> GRAPH_EVAL_LINEAR_WEIGHTS = {{
    {array_text(eval_model["weights"])}
}};

inline constexpr int SEARCH_RANKER_LINEAR_FEATURES = {ranker_model["feature_size"]};
inline constexpr float SEARCH_RANKER_LINEAR_BIAS = {ranker_model["bias"]:.8g}f;
inline constexpr std::array<float, SEARCH_RANKER_LINEAR_FEATURES> SEARCH_RANKER_LINEAR_WEIGHTS = {{
    {array_text(ranker_model["weights"])}
}};

}} // namespace lulzfish::eval::learned
"""
    path.write_text(text, encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, default=Path("data/lulzfish_training.jsonl"))
    parser.add_argument("--out-json", type=Path, default=Path("data/lulzfish_linear_models.json"))
    parser.add_argument("--out-header", type=Path, default=Path("data/lulzfish_linear_models.hpp"))
    parser.add_argument("--l2", type=float, default=1e-2)
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    records = load_records(args.data)
    eval_model = train_eval(records, args.l2)
    ranker_model = train_move_ranker(records, args.l2)
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps({"eval": eval_model, "search_ranker": ranker_model}, indent=2) + "\n",
        encoding="utf-8",
    )
    write_cpp_header(args.out_header, eval_model, ranker_model)
    print(f"wrote {args.out_json}")
    print(f"wrote {args.out_header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
